### ISSUE TITLE
Improve VUE architecture

### ISSUE THREAD

**Issue by kevinccbsg** [BRIKEV/tpv-tickets-front#14]
We have to improve some aspects of the APP

## Acceptance criteria

- [x] Add sass to the project
- [ ] Implement Vuex
- [x] Create a better folder structure with unit testing in some components
- [x] Add storybook
- [x] Add i18n

**Comment by bri06** [comment]
Is it worth adding vuex to the project?

**Comment by kevinccbsg** [comment]
I do not think so

**Comment by kevinccbsg** [comment]
This PR #20 closes this issue.
